#!/bin/bash

source ~/.bash_profile
git pull
npm install
rm -rf .next
npm run build
rm -rf www

mkdir www

cp -r .next/standalone/* www/
cp -r .next/standalone/.* www/
cp -r public www/public
cp -r .next/static www/.next/static
sed -i 's/const currentPort = parseInt(process.env.PORT, 10) || 3000/const currentPort = parseInt(process.env.PORT, 10) || 3001/' ./www/server.js

pm2 restart all